plugins {
    id 'java'
    id 'xyz.jpenilla.run-paper' version '3.1.0'
}

group = 'net.zlt.hangingheads'
version = plugin_version

base {
    archivesName = 'hanging-heads'
}

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${paper_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25}

processResources {
    var replaceProperties = [version: version]
    inputs.properties replaceProperties

    filesMatching('paper-plugin.yml') {
        expand replaceProperties
    }
}

tasks.named('runServer') {
    minecraftVersion '26.2'
}
